---
title: "Calidad del aire"
author: "César Cárdenas"
date: "9/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_condaenv("env_rstudio")
```

## Descripción

## Librerias

```{python}
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/cesar.cardenas/anaconda3/envs/env_rstudio/Library/plugins/platforms'

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb
import statsmodels.tsa.stattools as sts
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import grangercausalitytests
import statsmodels.graphics.tsaplots as sgt
from sklearn.metrics import mean_absolute_error, mean_squared_error

import warnings
warnings.simplefilter('ignore')
```

## Importación de datos

```{python}
df_comp = pd.read_csv('https://raw.githubusercontent.com/cccg8105/series-temporales-multivariantes/master/3.%20Casos%20de%20estudio%20en%20Python/E.%20Calidad%20del%20aire/AirQualityUCI.csv', parse_dates=[['Date', 'Time']],sep=';')
df_comp.head()
```

Se eliminan columnas en desuso

```{python}
df_comp = df_comp.drop(['Unnamed: 15'], axis = 1)
df_comp = df_comp.drop(['Unnamed: 16'], axis = 1)

df_comp.tail(10)
```
```{python}
df_comp.isnull().sum()
```
```{python}
np.arange(114)+9357

df_comp=df_comp.drop(np.arange(114)+9357,axis=0)
df_comp.tail()
```

```{python}
df_comp.dtypes
```

El tipo de datos de la columna Date_Time es un objeto y necesitamos cambiarlo a datetime. Además, para preparar los datos, necesitamos que el índice tenga fecha y hora.

```{python}
df_comp['Date_Time'] = pd.to_datetime(df_comp.Date_Time , format = '%d/%m/%Y %H.%M.%S',errors='coerce')
data = df_comp.drop(['Date_Time'], axis=1)
data.index = df_comp.Date_Time

data.tail()
```

```{python}
data.shape

for i in range(9357):
  data.iloc[i,0]=float(data.iloc[i,0].replace(',','.'))

for i in range(9357):
  data.iloc[i,3]=float(data.iloc[i,3].replace(',','.'))

for i in range(9357):
  data.iloc[i,10]=float(data.iloc[i,10].replace(',','.'))

for i in range(9357):
  data.iloc[i,11]=float(data.iloc[i,11].replace(',','.'))

for i in range(9357):
  data.iloc[i,12]=float(data.iloc[i,12].replace(',','.'))
data.head()
```

```{python}
data.dtypes
data['CO(GT)'] = data['CO(GT)'].astype(float)
data['C6H6(GT)'] = data['C6H6(GT)'].astype(float)
data['T'] = data['T'].astype(float)
data['RH'] = data['RH'].astype(float)
data['AH'] = data['AH'].astype(float)

data.dtypes
```

```{python}
data.isnull().sum()
```

En la descripción de los datos nos dice que algunos valores perdidos fueron sustituidos por el valor -200 así que nosotros vamos a cambiar eso y asignarles el valor inmediatamente anterior.

```{python}
cols = data.columns
for j in cols:
    for i in range(0,len(data)):
       if data[j][i] == -200:
           data[j][i] = data[j][i-1]
```

## Analisis exploratorio

```{python}
# Plot
fig, axes = plt.subplots(nrows=4, ncols=3, dpi=120, figsize=(10,6))
for i, ax in enumerate(axes.flatten()):
    datax = data[data.columns[i]]
    ax.plot(datax, color='red', linewidth=1)
    # Decorations
    ax.set_title(data.columns[i])
    ax.xaxis.set_ticks_position('none')
    ax.yaxis.set_ticks_position('none')
    ax.spines["top"].set_alpha(0)
    ax.tick_params(labelsize=6)

plt.tight_layout();
plt.show()
```

Matriz de correlación

```{python}
corr=data.corr()
corr
```

```{python}
plt.figure(figsize=(12, 9))
sb.heatmap(corr, xticklabels=corr.columns.values, yticklabels=corr.columns.values, annot=True,vmax=1, vmin=-1, cmap =sb.diverging_palette(220, 10, as_cmap=True),center=0 )
plt.show()
```

## Dividir contunto en entrenamiento y prueba

```{python}
n_obs=1000
X_train, X_test = data[0:-n_obs], data[-n_obs:]
print(X_train.shape, X_test.shape)
```

## Prueba de estacionariedad

```{python}
def augmented_dickey_fuller_statistics(time_series):
  result = sts.adfuller(time_series.values)
  print('p-value: %f' % result[1])

print('Test de Dickey-Fuller Aumentado:')
for i in range(13):
  print('Serie de tiempo Variable',i+1)
  augmented_dickey_fuller_statistics(X_train.iloc[:,i])

```

Todos los p-valores son menores que 0.05, con lo cual se rechaza la hipótesis nula de que la serie no es estacionaria. Conclusión: es estacionaria.

## Modelo VAR

```{python}
model = VAR(X_train)

modelsel=model.select_order(15)
print(modelsel.summary())

```

Ajustando el modelo

```{python}
res = model.fit(maxlags=15, ic='aic')
print(res.summary())
```

## Causalidad de Granger

```{python}
warnings.filterwarnings("ignore")
maxlag=15
test = 'ssr_chi2test'
def grangers_causality_matrix(X_train_transformed, variables, test = 'ssr_chi2test', verbose=False):
  dataset = pd.DataFrame(np.zeros((len(variables), len(variables))), columns=variables, index=variables)
  for c in dataset.columns:
    for r in dataset.index:
      test_result = grangercausalitytests(X_train_transformed[[r,c]], maxlag=maxlag, verbose=False)
      p_values = [round(test_result[i+1][0][test][1],4) for i in range(maxlag)]
      if verbose: 
        print(f'Y = {r}, X = {c}, P Values = {p_values}')
      min_p_value = np.min(p_values)
      dataset.loc[r,c] = min_p_value
  dataset.columns = [var + '_x' for var in variables]
  dataset.index = [var + '_y' for var in variables]
  return dataset
grangers_causality_matrix(X_train, variables = X_train.columns)
```

## Diagnosis del modelo

```{python}
residuals=res.resid

fig, axs = plt.subplots(13)
fig.suptitle('Gráficos de los residuos',fontsize=20)
fig.set_size_inches(18, 10)
[axs[i].plot(residuals.iloc[:,i]) for i in range(13)]
plt.show()

```

Prueba de estacionariedad de los residuos

```{python}
print('ADF de los Residuos, p-valores:')
[sts.adfuller(residuals.iloc[:,i])[1] for i in range(13)]
```


Todos los p-valores son < 0.05 por tanto se rechaza la hipótesis nula de que las 13 series de residuos no son estacionarias, por lo cual con un 95% de confianza se cree que son estacionarias.

Conclusión: Los residuos del modelo no presentan estructura de autocorrelación, son estacionarios según los resultados de la prueba de Dickey - Fuller aumentada y en los gráficos se puede comprobar esto visualmente, entonces puede concluirse que son ruido blanco como es deseable.

Valores predichos por el modelo

```{python}
y_fitted = res.fittedvalues
fig, axs = plt.subplots(13)
fig.suptitle('Gráficos de los valores predichos por el modelo',fontsize=20)
fig.set_size_inches(18, 10)
[axs[i].plot(y_fitted.iloc[:,i]) for i in range(13)]
plt.show()
```

## Predicciones

```{python}
lag_order = n_obs

# Input data para hacer forecasting (pronósticos a futuro)
input_data = X_train.values[-lag_order:]
# Forecasting
pred = res.forecast(y=input_data, steps=n_obs)
pred = (pd.DataFrame(pred, index=X_test.index, columns=X_test.columns + '_pred'))
print('Predicciones:')
pred
```

```{python}
plt.figure(figsize = (12, 10))
res.plot_forecast(lag_order)
plt.tight_layout(h_pad = 1.15)
plt.show()
```

```{python}
pred.columns=X_test.columns
pred
```

```{python}
# Actual vs Forecasted Plots
fig, axes = plt.subplots(nrows = int(len(X_train.columns)/2), ncols = 2, dpi = 100, figsize = (10,15))

for i, (col,ax) in enumerate(zip(X_train.columns, axes.flatten())):
    pred[col].plot(color = '#F4511E', legend = True, ax = ax).autoscale(axis =' x',tight = True)
    X_test[col].plot(color = '#3949AB', legend = True, ax = ax)

    ax.set_title('Sensor: ' + col + ' - Actual vs Forecast')
    ax.xaxis.set_ticks_position('none')
    ax.yaxis.set_ticks_position('none')

    ax.spines["top"].set_alpha(0)
    ax.tick_params(labelsize = 6)

plt.tight_layout()
plt.savefig('actual_forecast.png')
plt.show()
```

### Evaluando modelo

```{python}
cols=data.columns
for i in cols:
    print('RMSE value for', i, 'is : ', np.sqrt(mean_squared_error(pred[i], X_test[i])))

```

