---
title: "Mercado Financiero Europeo"
output: html_notebook
author: "César Cárdenas"
date: "31/3/2021"
---

### Librerias

```{r message=FALSE, warning=FALSE, include=FALSE}
# install.packages("vars")
# install.packages("MTS")
# install.packages("tseries")
# install.packages("ggfortify")
library(readr)
library(tseries)
library(ggplot2)
library(ggfortify)
library(dplyr)
library(vars)
library(MTS) # diffM

# Plot avanzado con separación visual entre lo real y lo pronosticado
library(lattice)
library(grid)
library(zoo)
```

### Importación de datos

```{r}
data(EuStockMarkets)

head(EuStockMarkets)

frequency(EuStockMarkets)
start(EuStockMarkets)

autoplot(EuStockMarkets)
```

### Dividir en entrenamiento y prueba

```{r}
n_obs=30
end=dim(EuStockMarkets)[1]
X_train = EuStockMarkets[1:(end-n_obs),]
X_test = EuStockMarkets[(end-n_obs+1):end,]
dim(X_test)
```

### Prueba de estacionariedad

```{r}
apply(X_train, 2, adf.test) #2 para especificar que lo queremos aplicar por columnas
```

Diferenciación de la serie de tiempo

```{r}
stnry = diffM(X_train)

# Volviendo a hacer el test:
apply(stnry, 2, adf.test)

plot.ts(stnry)
```

### Modelo

```{r}
VARselect(stnry, type = "none", lag.max = 10)


# Creando el modelo
var.a <- vars::VAR(stnry,
                   lag.max = 10,
                   ic = "AIC",
                   type = "none")

summary(var.a)
```

### Causalidad de Granger

```{r}
# Causalidad de Granger 
causality(var.a, cause = c("DAX"))
causality(var.a, cause = c("SMI"))
causality(var.a, cause = c("CAC"))
causality(var.a, cause = c("FTSE"))

```

Diagnosis del modelo

```{r}
# Diagnosis del modelo (Portmanteau test para objetos var)
serial.test(var.a)
# Deseamos obtener un p-valor > 0.05, en este caso no lo obtenemos.
# Posibles soluciones:
# a) Cambiar el orden del modelo.
# b) Cambiar el tipo de modelo.
# c) Añadir otro paso de diferenciación o transformar con logaritmos.

# Estos modelos son a menudo tan complejos que no se puede alcanzar un resultado completamente 
# satisfactorio sin cambiar mucho los datos con logaritmos o varios pasos de diferencias.
```

### Predicción de variable DAX

```{r}
fcast = predict(var.a, n.ahead = 30)
plot(fcast)

# Solo para DAX 
DAX = fcast$fcst[1]; DAX 

# Extrayendo la columna de pronósticos
x = DAX$DAX[,1]; x

# Invirtiendo la diferenciación
tail(X_train)

x = cumsum(x) + + X_train[nrow(X_train), 1]

plot.ts(x)

```

Combinando con datos reales

```{r}
start(EuStockMarkets)
frequency(EuStockMarkets)

DAXinv =ts(c(X_train[,1], x),
           start = c(1991,130), frequency = 260)


# Dibujando todo 
plot(DAXinv)
plot.ts(DAXinv[1760:1860])

```

```{r}
# Objeto zoo
xx = zoo(DAXinv[1760:1860])


# En el parámetro grid.clip ponemos la cantidad de observaciones que son reales dentro de las 
# que hemos elegido. Hemos cogido 101 de las que 30 son pronósticos, así que grid.clip sería 71-1

xyplot(xx, grid=TRUE, panel = function(xx, y, ...){
  
  panel.xyplot(xx, y, col="red", ...)
  
  grid.clip(unit(70, "native"), just=c("right")) 
  
  panel.xyplot(xx, y, col="green", ...) })

```

