---
title: "Datos Macroeconomicos"
output: html_notebook
author: "César Cárdenas"
date: "31/3/2021"
---

### Librerias

```{r message=FALSE, warning=FALSE, include=FALSE}
# install.packages("vars")
# install.packages("MTS")
# install.packages("tseries")
# install.packages("ggfortify")
library(readr)
library(tseries)
library(ggplot2)
library(ggfortify)
library(dplyr)
library(vars)
library(MTS) # diffM

# Plot avanzado con separación visual entre lo real y lo pronosticado
library(lattice)
library(grid)
library(zoo)
```

### Importación de datos

```{r}
dat = read_csv('https://raw.githubusercontent.com/cccg8105/series-temporales-multivariantes/master/2.%20Casos%20de%20estudio%20en%20R/E.%20Datos%20macroecon%C3%B3micos%20de%20mayor%20dimensi%C3%B3n/Mac_Ric.csv')

head(dat)
```

Creación de serie temporal

```{r}
plot(ts(dat$LREERS,start=c(1970,1),freq=4),ylab="LREERS") # logarithm of real effective exchange rate
plot(ts(dat$RIRR,start=c(1970,1),freq=4),ylab="RIRR") # real interest rate relative to trading partners
plot(ts(dat$LRGDPPCR,start=c(1970,1),freq=4),ylab="LRGDPPCR") # logarithm of real GDP per capita relative to trading partners
plot(ts(dat$LPR2COMM5,start=c(1970,1),freq=4),ylab="LPR2COMM5") # real commodity prices
plot(ts(dat$OPENY,start=c(1970,1),freq=4),ylab="OPENY") # openness - ratio to GDP of exports and imports
plot(ts(dat$FBYA,start=c(1970,1),freq=4),ylab="FBYA") # ratio of fiscal balance to GDP
plot(ts(dat$NFAOFPY,start=c(1970,1),freq=4),ylab="NFAOFPY") # ratio to GDP of net foreign assets of the banking system

```
### Modeo VAR 

Con variables exogenas

```{r}
#Variables endógenas
dat.VAR <- cbind(dat$LREERS,dat$RIRR,dat$LRGDPPCR,dat$LPR2COMM5,dat$OPENY,dat$FBYA,dat$NFAOFPY)
colnames(dat.VAR) <- c("LREERS","RIRR","LRGDPPCR","LPR2COMM5","OPENY","FBYA","NFAOFPY")

#Variables exógenas
dat.EXO <- cbind(dat$SDUMC1,dat$SDUMC2,dat$SDUMC3,dat$DUMRER1,dat$DUMRER2,dat$DUMFBYA,dat$DUMNFAOFPY)
colnames(dat.EXO) <- c("SDUMC1","SDUMC2","SDUMC3","DUMRER1","DUMRER2","DUMFBYA","NFAOFPY")

# Eliminar las variables de variables con valores solo cero
dat.EXO=dat.EXO[,1:3]

# Crear el modelo VAR con "exog==dat.EXO"
VAR.est <- vars::VAR(dat.VAR,lag.max=10, ic="AIC",type="const",exog=dat.EXO)
summary(VAR.est)
```

Sin variables exogenas

```{r}
####### Modelo VAR sin variables exógenas:
VAR.est2 <- vars::VAR(dat.VAR,lag.max=10, ic="AIC",type="const")
summary(VAR.est2)
```

### Predicciones

```{r}
####### Predicciones
predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "LREERS")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "RIRR")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "LRGDPPCR")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "LPR2COMM5")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "OPENY")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "FBYA")

predictions <- predict(VAR.est2, n.ahead = 10, ci = 0.95)
plot(predictions, names = "NFAOFPY")

```

